[DEFAULT]
migration_table = _yoyo_migration
batch_mode = on
sources = src/migrations

; database = postgresql://postgres:root@localhost:5432/portfolio_db

database = postgresql://neondb_owner:npg_n0T5molwGIOX@ep-steep-shadow-aoo7ckf9.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
